[package]
name = "dotlottie-ffi"
version = "0.1.31"
edition = "2021"
build = "build.rs"

[profile.release]
lto = true
opt-level = "z"
strip = true 
codegen-units = 1
panic = "abort" 

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "dotlottie_player"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.25", features = ["cli"] }
dotlottie-rs = { path = "../dotlottie-rs", features = ["thorvg"] }
cfg-if = "1.0"
bitflags = "2.6.0"

[build-dependencies]
uniffi = { version = "0.25", features = ["build"] }
lazy_static = "1.4"
cbindgen = "0.26.0"
