[package]
name = "dotlottie-ffi"
version = "0.1.38"
edition = "2021"
build = "build.rs"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "dotlottie_player"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["thorvg_v0"]
thorvg_v0 = ["dotlottie-rs/thorvg_v0"]
thorvg_v1 = ["dotlottie-rs/thorvg_v1"]
thorvg_v1_sw = ["dotlottie-rs/thorvg_v1_sw"]
thorvg_v1_gl = ["dotlottie-rs/thorvg_v1_gl"]
thorvg_v1_wg = ["dotlottie-rs/thorvg_v1_wg"]

[dependencies]
uniffi = { version = "0.25", features = ["cli"] }
dotlottie-rs = { path = "../dotlottie-rs", default-features = false }
cfg-if = "1.0"
bitflags = "2.6.0"

[build-dependencies]
uniffi = { version = "0.25", features = ["build"] }
lazy_static = "1.4"
cbindgen = "0.26.0"
