[github]
owner = 'LottieFiles'
repo = 'dotlottie-rs'

[package]
versioned_files = ["dotlottie-ffi/Cargo.toml"]

[[package.assets]]
path = "release/dotlottie-player.darwin.tar.gz"
name = "dotlottie-player.darwin.tar.gz"

[[package.assets]]
path = "release/dotlottie-player.android.tar.gz"
name = "dotlottie-player.android.tar.gz"

[[package.assets]]
path = "release/dotlottie-player.wasm.tar.gz"
name = "dotlottie-player.wasm.tar.gz"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\" && git push"

[workflows.steps.variables]
"$version" = "Version"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"
