[github]
owner = 'LottieFiles'
repo = 'dotlottie-rs'

[package]
versioned_files = ["dotlottie-ffi/Cargo.toml"]
changelog = "CHANGELOG.md"

[[package.assets]]
path = "release/dotlottie-player.darwin.tar.gz"
name = "dotlottie-player.darwin.tar.gz"

[[package.assets]]
path = "release/dotlottie-player.android.tar.gz"
name = "dotlottie-player.android.tar.gz"

[[package.assets]]
path = "release/dotlottie-player.wasm.tar.gz"
name = "dotlottie-player.wasm.tar.gz"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: Release $version\" && git push --force --set-upstream origin release"

[workflows.steps.variables]
"$version" = "Version"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: Release $version"
variables = { "$version" = "Version" }

[workflows.steps.body]
template = "This PR was created by Knope. Merging it will create a new release\n\n$changelog"
variables = { "$changelog" = "ChangelogEntry" }

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"
