[package]
name = "demo-player"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.28"
dotlottie-rs = { path = "../../dotlottie-rs", features = ["tvg-v1", "tvg-sw", "tvg-png", "tvg-jpg", "tvg-webp", "tvg-threads", "tvg-lottie-expressions", "tvg-gl", "tvg-wg"] }
