[package]
name = "demo-player"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27"
dotlottie-rs = { path = "../../dotlottie-rs" }
sysinfo = "0.30"
rand = "0.8"

[[bin]]
name = "star-rating"
path = "src/bin/star-rating/star-rating.rs"


[[bin]]
name = "exploding-pigeon"
path = "src/bin/exploding-pigeon/exploding-pigeon.rs"

[[bin]]
name = "play-on-hover"
path = "src/bin/play-on-hover/play-on-hover.rs"
