name: Build Artifacts

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: "Target to build"
        required: true
        options:
          - "apple"
          - "android"
          - "linux"
          - "wasm"
          - "windows"
          - "all"
      commitSHA:
        description: "Commit SHA (leave blank for default branch)"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.target }}-${{ github.event.inputs.commitSHA || github.ref }}
  cancel-in-progress: true

jobs:
  build-apple:
    runs-on: macos-latest-large
    if: github.event.inputs.target == 'apple' || github.event.inputs.target == 'all'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitSHA || github.ref }}

      - uses: Homebrew/actions/setup-homebrew@master
      - uses: ningenMe/setup-rustup@v1.1.0

      - name: Install Make
        run: brew install make

      - name: Install Apple targets
        run: make install-apple-targets
        working-directory: dotlottie-ffi

      - name: Build Apple
        run: make apple
        working-directory: dotlottie-ffi

      - name: Upload Apple Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotlottie-player.apple.tar.gz
          path: dotlottie-ffi/release/apple/dotlottie-player.apple.tar.gz
          if-no-files-found: error

  build-android:
    runs-on: ubuntu-latest
    if: github.event.inputs.target == 'android' || github.event.inputs.target == 'all'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitSHA || github.ref }}

      - name: Setup Rust
        uses: ningenMe/setup-rustup@v1.1.0

      - name: Install uniffi-bindgen-cpp
        run: cargo install uniffi-bindgen-cpp

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28b

      - name: Install Android targets
        run: make install-android-targets
        working-directory: dotlottie-ffi

      - name: Build Android
        run: make android
        working-directory: dotlottie-ffi
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Check ELF Alignment
        run: ./scripts/check_elf_alignment.sh dotlottie-ffi/release/android/dotlottie-player/src/main/jniLibs

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotlottie-player.android.tar.gz
          path: dotlottie-ffi/release/android/dotlottie-player.android.tar.gz
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    if: github.event.inputs.target == 'linux' || github.event.inputs.target == 'all'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitSHA || github.ref }}

      - name: Setup Rust
        uses: ningenMe/setup-rustup@v1.1.0

      - name: Install uniffi-bindgen-cpp
        run: cargo install uniffi-bindgen-cpp

      - name: Install Linux targets
        run: make install-linux-targets
        working-directory: dotlottie-ffi

      - name: Build Linux
        run: make linux
        working-directory: dotlottie-ffi

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotlottie-player.linux.tar.gz
          path: dotlottie-ffi/release/linux/dotlottie-player.linux.tar.gz
          if-no-files-found: error

  build-wasm:
    runs-on: ubuntu-latest
    if: github.event.inputs.target == 'wasm' || github.event.inputs.target == 'all'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitSHA || github.ref }}

      - name: Setup Rust
        uses: ningenMe/setup-rustup@v1.1.0

      - name: Install uniffi-bindgen-cpp
        run: cargo install uniffi-bindgen-cpp

      - name: Install Binaryen
        run: |
          sudo apt-get update
          sudo apt-get install -y binaryen

      - name: Install WASM targets
        run: make install-wasm-targets
        working-directory: dotlottie-ffi

      - name: Install Emscripten SDK
        run: make wasm-install-emsdk
        working-directory: dotlottie-ffi

      - name: Build WASM
        run: make wasm
        working-directory: dotlottie-ffi

      - name: Optimize WASM
        run: wasm-opt dotlottie-ffi/build/wasm/DotLottiePlayer.wasm -o dotlottie-ffi/build/wasm/DotLottiePlayer.wasm -all -Oz

      - name: Upload WASM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotlottie-player.wasm.tar.gz
          path: dotlottie-ffi/release/wasm/dotlottie-player.wasm.tar.gz
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    if: github.event.inputs.target == 'windows' || github.event.inputs.target == 'all'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitSHA || github.ref }}

      - name: Setup Rust
        uses: ningenMe/setup-rustup@v1.1.0

      - name: Install uniffi-bindgen-cpp
        run: cargo install uniffi-bindgen-cpp

      - name: Install Windows targets
        run: make install-windows-targets
        working-directory: dotlottie-ffi

      - name: Build Windows
        run: make windows
        working-directory: dotlottie-ffi

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotlottie-player.windows.tar.gz
          path: dotlottie-ffi/release/windows/dotlottie-player.windows.tar.gz
          if-no-files-found: error
